### ISSUE TITLE
vifmimg: line 11: No such file or directory

### ISSUE THREAD

**Issue by SciPhys** [cirala/vifmimg#25]
I am using the latest scripts and ran make install. I am using vifmrun to start vifm. This happends for both images and pdf. What can be the reason and how can I fix this?. Error shows like [this](https://imgur.com/ox5OyZU.png)

**Comment by sQVe** [comment]
You have very likely not installed the dependencies needed for the scripts. Read https://github.com/cirala/vifmimg#prerequisites.

**Comment by SciPhys** [comment]
Okay, lemme go through all the dependencies once again and I will update here.

**Comment by SciPhys** [comment]
The issue is solved. I have a rough idea of the problem and I will try to describe here for anyone else having the problem. 

**_To summarize I think the path, where ueberzug was installed, wasn't added to the $PATH variable. Either do `export PATH=$PATH:/path/to/ueberzug_scripts` or better put it in bashrc/zshrc_** (if this doesn't fix do the steps below)

1. While doing `pip3 install ueberzug` , ueberzug did get installed but it was not build properly as required. This was due to missing missing python3-wheel (atleast in my system). Installing python3-wheel (for mx-linux or debian based ones, `sudo apt-get install python3-wheel`) after ueberzug didn't fix it.
2. So remove ueberzug (`pip3 uninstall ueberzug`). Install python3-wheel if not already. Do `pip3 install ueberzug` again.

**Comment by sQVe** [comment]
@SciPhy-Two 👍🏼 Please close the issue if you feel that it's solved!

**Comment by plum** [comment]
I too have experienced this problem since upgrading to the latest versions of the scripts.
I am running archlinux. I followed the advice given by sQVe to no avail; I already have python3-wheel, and tried re-installing ueberzug with pip3, and I also tried re-installing ueberzug from arch repository, with same result. 

I experience this same problem with all filetypes. All dependencies have been checked.


I used to use the scripts with no problem before May, with great joy! I'm Not sure what to try next now. I cannot think of any route, but need advice.
